
export interface LoadStop {
  stopIndex: number;
  warehouseCode: string;
  loadingType: string; // e.g. '地板' | '卡板'
  appointmentTime?: string; // Optional specific time for this stop
  address?: string; // Optional full address for navigation
}

export interface Load {
  id?: string; // ID is now optional for creation (generated by DB)
  created_at?: string; // Generated by DB
  type: 'Amazon FBA' | '海外仓/自家仓';
  originCity: string; // Mapped to origin_city in DB
  destinationState: string; // Mapped to destination_state in DB
  warehouseCode: string; // Mapped to warehouse_code in DB
  stops: LoadStop[];     
  price?: number;
  mustAppt: boolean; // Mapped to must_appt in DB
  notes?: string;        
  contactPhone: string; // Mapped to contact_phone in DB
  contactName: string; // Mapped to contact_name in DB
  status: 'active' | 'booked';
}
